# .github/workflows/ci.yml
name: Monorepo tests

on:
  push:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      firebase-vercel: ${{ steps.filter.outputs.firebase-vercel }}
      koa: ${{ steps.filter.outputs.koa }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            firebase-vercel:
              - 'firebase-vercel/**'
            koa:
              - 'koa/**'

  test-firebase-vercel:
    needs: changes
    if: needs.changes.outputs.firebase-vercel == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v3
        with:
          version: 10
                # Pull environment variables from Vercel
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Variables
        run: vercel env pull .env.local
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        working-directory: firebase-vercel
      - run: cd firebase-vercel && pnpm install && pnpm test

  test-koa:
    needs: changes
    if: needs.changes.outputs.koa == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - run: cd koa && pnpm install && pnpm test